# common
model_name: wayformer

# model
use_map_image: False
use_map_lanes: True
num_modes: 6
num_agent_feature: 12 # 5 (x,y,vx,vy,heading) + 2 (size) + 5 (type one-hot)
num_map_feature: 8 # 3 (x,y, heading) + 4 (lane type one-hot) + 1 (intersection one-hot) 
hidden_size: 256
num_encoder_layers: 2
num_decoder_layers: 8
tx_hidden_size: 1024
tx_num_heads: 4
dropout: 0.1
entropy_weight: 40.0
kl_weight: 20.0
use_FDEADE_aux_loss: True
num_queries_dec: 64
num_queries_enc: 192

# train
max_epochs: 150 #150 #40
learning_rate: 0.0001 # 0.00075 # 1e-3 for lanegcn
learning_rate_sched: [ 10, 20, 30, 40, 50 ]
optimizer: AdamW #According to PyTorch naming
scheduler: multistep # plateau, multistep
ewc_lambda: 2000
grad_clip_norm: 5
train_batch_size: 32 #32 #128
eval_batch_size: 128 #32 #128

# data related
max_num_agents: 32
map_range: 100
max_num_roads: 384
max_points_per_lane: 30 # will be overwritten if manually_split_lane is True
manually_split_lane: False
# lane split related params
point_sampled_interval: 1
num_points_each_polyline: 20
vector_break_dist_thresh: 1.0

