# common
model_name: autobot
num_modes: 10
hidden_size: 128
num_encoder_layers: 2
num_decoder_layers: 2
tx_hidden_size: 384
tx_num_heads: 16
dropout: 0.1
entropy_weight: 40.0
kl_weight: 20.0
use_FDEADE_aux_loss: True
predict_yaw: False
k_attr: 5
map_attr: 2

# train
max_epochs: 150 # 150`
learning_rate: 0.00075
learning_rate_sched: [10, 20, 30, 40, 50]
adam_epsilon: 1e-4
optimizer: Adam #According to PyTorch naming
scheduler: multistep # plateau, multistep
train_batch_size: 64 #64
eval_batch_size: 2
grad_clip_norm: 5

# data related
map_range: 150 # The distance included in
point_sampled_interval: 1 # only used when manually_split_lane is True, the interval of points sampled from the original lane
num_points_each_polyline: 20 # only used when manually_split_lane is True, the number of points in each polyline
vector_break_dist_thresh: 1.0 # only used when manually_split_lane is True, the distance threshold to break the vector to split the lane
